# Generated by Django 4.2.15 on 2024-08-31 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0005_alter_crypto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='title',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
