# Generated by Django 4.2.15 on 2024-09-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0007_network_crypto_networks'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='full_name',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='networks',
            field=models.ManyToManyField(related_name='networks', to='crypto.network'),
        ),
    ]
