# Generated by Django 4.2.15 on 2024-09-02 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0010_alter_crypto_slug_alter_crypto_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='crypto',
            unique_together={('title', 'slug', 'full_name')},
        ),
    ]
