# Generated by Django 4.2.15 on 2024-09-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0011_alter_crypto_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='full_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
