# Generated by Django 4.2.15 on 2024-08-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_alter_crypto_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crypto',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddIndex(
            model_name='crypto',
            index=models.Index(fields=['-time_create'], name='crypto_cryp_time_cr_42fa6c_idx'),
        ),
    ]
