# Generated by Django 4.2.15 on 2024-09-02 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0008_crypto_full_name_alter_crypto_networks'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='crypto',
            unique_together={('title', 'slug')},
        ),
    ]
