# Generated by Django 4.2.15 on 2024-09-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0009_alter_crypto_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='title',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
